# Generated by Django 2.1.5 on 2019-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cities',
            field=models.ManyToManyField(to='api.City'),
        ),
    ]
