# Generated by Django 2.1.5 on 2019-02-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ammenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammenity',
            name='icon',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
