# Generated by Django 2.1.5 on 2019-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190206_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mode',
            field=models.CharField(choices=[('A', 'Arriendo'), ('C', 'Compra')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
