# Generated by Django 2.1.5 on 2019-02-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190206_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.FloorPlan'),
        ),
        migrations.AddField(
            model_name='property',
            name='garages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.ManyToManyField(to='api.Picture'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('A', 'Público'), ('B', 'Privado'), ('C', 'Borrador')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('A', 'Apartamentos'), ('B', 'Bodegas'), ('C', 'Casas'), ('D', 'Consultorios'), ('E', 'Edificio de oficinas'), ('F', 'Edificio de apartamentos'), ('G', 'Fincas'), ('H', 'Locales'), ('I', 'Lotes'), ('J', 'Oficinas')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
