# Generated by Django 2.1.5 on 2019-02-06 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20190206_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('A', 'Free'), ('B', 'Agent'), ('C', 'Pro'), ('D', 'Enterprise')], max_length=100)),
                ('avatar', models.ImageField(default='users/avatars/user.jpg', upload_to='users/avatars/')),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='owner',
        ),
        migrations.AlterField(
            model_name='property',
            name='mode',
            field=models.CharField(choices=[('A', 'Arriendo'), ('B', 'Compra')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
